version: "3"
services:
  postgres:
    container_name: "auth_psql"
    image: postgres:12.0-alpine
    env_file:
      - ./docker/postgres/.env.example
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
  nginx:
    image: nginx:alpine
    container_name: "auth_nginx"
    ports:
      - "8001:80"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - .:/var/www
    depends_on:
      - auth
  auth:
    image: auth_medicine:alpine
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: "auth_medicine"
    volumes:
      - ./:/var/www
    depends_on:
      - postgres
volumes:
  postgres_data:
  pgadmin:
