version: "3"
services:
  postgres:
    container_name: "medicine_psql"
    image: postgres:12.0-alpine
    env_file:
      - ./docker/postgres/.env.example
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
  nginx:
    image: nginx:alpine
    container_name: "medicine_nginx"
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - .:/var/www
    depends_on:
      - medicine
    networks:
      - oauth-network
  medicine:
    image: medicine_medicine:alpine
    hostname: "medicine_app"
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: "medicine_app"
    volumes:
      - ./:/var/www
    networks:
      - default
      - oauth-network
volumes:
  postgres_data:
networks:
    default:
    oauth-network:
        name: "auth_oauth-net"
        external: true
